
import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  { barcode: '89012345', name: 'Premium Biscuits', price: 45, weight: 200, category: 'Snacks', location: { x: 62, y: 12, zone: 'A-3' } },
  { barcode: '89056789', name: 'Fresh Milk 1L', price: 60, weight: 1000, category: 'Dairy', location: { x: 37, y: 62, zone: 'A-10' } },
  { barcode: '89098765', name: 'Chocolate Bar', price: 20, weight: 50, category: 'Snacks', location: { x: 12, y: 37, zone: 'A-5' } },
  { barcode: '89011223', name: 'Instant Noodles', price: 12, weight: 70, category: 'Pantry', location: { x: 87, y: 87, zone: 'A-16' } },
  { barcode: '89033445', name: 'Fruit Juice 1L', price: 95, weight: 1050, category: 'Beverages', location: { x: 12, y: 12, zone: 'A-1' } },
];

export const WAIT_WINDOW_MS = 5000;

const DEFAULT_OFFERS = [
  { id: 1, title: 'Summer Dairy Sale', desc: 'Flat 10% OFF on all Milk', code: 'DAIRY10', gradient: 'from-blue-500 to-cyan-400', icon: 'fa-cow' },
  { id: 2, title: 'Snack Attack', desc: 'Buy 2 get 1 FREE on Biscuits', code: 'SNACKFREE', gradient: 'from-orange-500 to-amber-400', icon: 'fa-cookie' },
  { id: 3, title: 'Weekend Special', desc: '₹50 cashback above ₹500', code: 'WKD50', gradient: 'from-violet-600 to-fuchsia-500', icon: 'fa-star' },
  { id: 4, title: 'New User Offer', desc: '₹100 discount first scan', code: 'HELLO100', gradient: 'from-emerald-600 to-teal-400', icon: 'fa-gift' },
];

const DEFAULT_PRODUCT_NAMES: Record<string, string> = {
  '89012345': 'Premium Biscuits',
  '89056789': 'Fresh Milk 1L',
  '89098765': 'Chocolate Bar',
  '89011223': 'Instant Noodles',
  '89033445': 'Fruit Juice 1L',
  'unknown': 'Unscanned Item'
};

export const TRANSLATIONS = {
  en: {
    cart_title: "SmartTrolley",
    live_load: "Live Load",
    subtotal: "Subtotal",
    syncing: "Syncing Data...",
    syncing_sub: "Matching weight shift with inventory.",
    security_flag: "Security Flag",
    unscanned_detected: "Unscanned item(s) detected.",
    items_count: "Cart Items",
    guide_title: "Smart Guide",
    optimized_path: "Aisle Optimized",
    pick_here: "Pick Here",
    walking: "Walking",
    meters: "METERS",
    list_title: "My Smart List",
    hunter_placeholder: "What are we hunting today?",
    deals_title: "Flash Deals",
    scan_req: "Scan Required",
    verified: "Verified",
    reset: "Reset Trolley",
    empty_cart: "Your trolley feels a bit light...",
    personal_planner: "Personal Planner",
    gps_linked: "GPS Linked",
    list_empty: "List is empty",
    up_next: "Coming Up Next",
    main_dest: "Main Destination",
    scan_tip: "Scan items as you pick them up to auto-update your path.",
    billing_title: "Order Summary",
    unscanned_alert: "Unscanned Items Detected",
    unscanned_desc: "Please scan or remove unscanned items before paying.",
    gst: "GST (18%)",
    grand_total: "Grand Total",
    pay_qr: "Scan UPI QR Code",
    pay_card: "Pay via Card",
    pay_success: "Payment Successful!",
    receipt_sent: "Digital receipt has been sent to your email.",
    close_new: "Close & Start New Shopping",
    claim: "Claim",
    empty_billing_prompt: "Add items to generate a bill",
    receipt_header: "SMART STORE RECEIPT",
    txn_id: "Transaction ID",
    scan_to_pay: "Scan to Pay",
    terminal: "Store Terminal",
    confirm_payment: "Confirm Payment",
    cancel: "Cancel",
    code_label: "CODE",
    north_facing: "North-Facing",
    products: DEFAULT_PRODUCT_NAMES,
    offers: DEFAULT_OFFERS
  },
  hi: {
    cart_title: "स्मार्ट ट्रॉली",
    live_load: "कुल वजन",
    subtotal: "कुल राशि",
    syncing: "डेटा सिंक हो रहा है...",
    syncing_sub: "इन्वेंट्री के साथ वजन मिलान।",
    security_flag: "सुरक्षा चेतावनी",
    unscanned_detected: "बिना स्कैन किया हुआ सामान मिला।",
    items_count: "कार्ट का सामान",
    guide_title: "मार्गदर्शक",
    optimized_path: "इष्टतम रास्ता",
    pick_here: "यहाँ से उठाएं",
    walking: "दूरी",
    meters: "मीटर",
    list_title: "मेरी सूची",
    hunter_placeholder: "आज आप क्या ढूंढ रहे हैं?",
    deals_title: "आज के ऑफर",
    scan_req: "स्कैन जरूरी",
    verified: "सत्यापित",
    reset: "ट्रॉली खाली करें",
    empty_cart: "आपकी ट्रॉली खाली लग रही है...",
    personal_planner: "पर्सनल प्लानर",
    gps_linked: "GPS लिंक",
    list_empty: "सूची खाली है",
    up_next: "अगला सामान",
    main_dest: "मुख्य मंजिल",
    scan_tip: "सामान उठाते समय स्कैन करें ताकि आपका रास्ता अपडेट हो सके।",
    billing_title: "ऑर्डर सारांश",
    unscanned_alert: "बिना स्कैन किया सामान मिला",
    unscanned_desc: "भुगतान करने से पहले कृपया सामान स्कैन करें या हटाएं।",
    gst: "जीएसटी (18%)",
    grand_total: "कुल योग",
    pay_qr: "UPI QR कोड स्कैन करें",
    pay_card: "कार्ड से भुगतान",
    pay_success: "भुगतान सफल रहा!",
    receipt_sent: "डिजिटल रसीद आपके ईमेल पर भेज दी गई है।",
    close_new: "बंद करें और नया शॉपिंग शुरू करें",
    claim: "प्राप्त करें",
    empty_billing_prompt: "बिल बनाने के लिए सामान जोड़ें",
    receipt_header: "स्मार्ट स्टोर रसीद",
    txn_id: "लेनदेन आईडी",
    scan_to_pay: "भुगतान के लिए स्कैन करें",
    terminal: "स्टोर टर्मिनल",
    confirm_payment: "भुगतान की पुष्टि करें",
    cancel: "रद्द करें",
    code_label: "कोड",
    north_facing: "उत्तर दिशा",
    products: {
      '89012345': 'प्रीमियम बिस्कुट',
      '89056789': 'ताजा दूध 1ली',
      '89098765': 'चॉकलेट बार',
      '89011223': 'इंस्टेंट नूडल्स',
      '89033445': 'फलों का रस 1ली',
      'unknown': 'बिना स्कैन किया सामान'
    },
    offers: [
      { id: 1, title: 'डेयरी सेल', desc: 'दूध पर 10% की छूट', code: 'DAIRY10', gradient: 'from-blue-500 to-cyan-400', icon: 'fa-cow' },
      { id: 2, title: 'स्नैक ऑफर', desc: 'बिस्कुट पर 2 खरीदें 1 मुफ्त', code: 'SNACKFREE', gradient: 'from-orange-500 to-amber-400', icon: 'fa-cookie' },
      { id: 3, title: 'वीकेंड स्पेशल', desc: '₹500 से ऊपर ₹50 कैशबैक', code: 'WKD50', gradient: 'from-violet-600 to-fuchsia-500', icon: 'fa-star' },
      { id: 4, title: 'नया यूजर ऑफर', desc: 'पहले स्कैन पर ₹100 छूट', code: 'HELLO100', gradient: 'from-emerald-600 to-teal-400', icon: 'fa-gift' },
    ]
  },
  ta: {
    cart_title: "ஸ்மார்ட் ட்ராலி",
    live_load: "நேரடி எடை",
    subtotal: "மொத்தம்",
    syncing: "தரவு ஒத்திசைக்கப்படுகிறது...",
    syncing_sub: "சரக்கு மாற்றத்துடன் எடையைப் பொருத்துதல்.",
    security_flag: "பாதுகாப்பு எச்சரிக்கை",
    unscanned_detected: "ஸ்கேன் செய்யப்படாத பொருட்கள் கண்டறியப்பட்டன.",
    items_count: "கூடை பொருட்கள்",
    guide_title: "வழிகாட்டி",
    optimized_path: "வழிமுறை மேம்படுத்தப்பட்டது",
    pick_here: "இங்கே எடுக்கவும்",
    walking: "நடப்பது",
    meters: "மீட்டர்",
    list_title: "எனது பட்டியல்",
    hunter_placeholder: "இன்று நீங்கள் என்ன தேடுகிறீர்கள்?",
    deals_title: "சலுகைகள்",
    scan_req: "ஸ்கேன் தேவை",
    verified: "சரிபார்க்கப்பட்டது",
    reset: "கூடையை காலியாக்கு",
    empty_cart: "உங்கள் கூடை காலியாக உள்ளது...",
    personal_planner: "தனிப்பட்ட திட்டமிடுபவர்",
    gps_linked: "ஜிபிஎஸ் இணைக்கப்பட்டது",
    list_empty: "பட்டியல் காலியாக உள்ளது",
    up_next: "அடுத்து வருவது",
    main_dest: "முக்கிய இலக்கு",
    scan_tip: "பொருட்களை எடுக்கும்போது ஸ்கேன் செய்யவும்.",
    billing_title: "ஆர்டர் சுருக்கம்",
    unscanned_alert: "ஸ்கேன் செய்யப்படாத பொருட்கள்",
    unscanned_desc: "பணம் செலுத்தும் முன் பொருட்களை ஸ்கேன் செய்யவும்.",
    gst: "ஜிஎஸ்டி (18%)",
    grand_total: "மொத்த தொகை",
    pay_qr: "UPI QR ஸ்கேன்",
    pay_card: "கார்டு மூலம் பணம்",
    pay_success: "பணம் செலுத்துதல் வெற்றி!",
    receipt_sent: "டிஜிட்டல் ரசீது அனுப்பப்பட்டது.",
    close_new: "புதிய ஷாப்பிங் தொடங்கவும்",
    claim: "பெறுக",
    empty_billing_prompt: "பில் உருவாக்க பொருட்களை சேர்க்கவும்",
    receipt_header: "ஸ்மார்ட் ஸ்டோர் ரசீது",
    txn_id: "பரிவர்த்தனை ஐடி",
    scan_to_pay: "பணம் செலுத்த ஸ்கேன் செய்க",
    terminal: "டெர்மினல்",
    confirm_payment: "பணம் செலுத்துவதை உறுதிப்படுத்து",
    cancel: "ரத்து செய்",
    code_label: "குறியீடு",
    north_facing: "வடக்கு நோக்கியது",
    products: {
      '89012345': 'பிரீமியம் பிஸ்கட்',
      '89056789': 'புதிய பால் 1லி',
      '89098765': 'சாக்லேட் பார்',
      '89011223': 'நூடுல்ஸ்',
      '89033445': 'பழச்சாறு 1லி',
      'unknown': 'ஸ்கேன் செய்யப்படாத பொருள்'
    },
    offers: [
      { id: 1, title: 'பால் விற்பனை', desc: 'பாலுக்கு 10% தள்ளுபடி', code: 'DAIRY10', gradient: 'from-blue-500 to-cyan-400', icon: 'fa-cow' },
      { id: 2, title: 'பிஸ்கட் சலுகை', desc: '2 வாங்கினால் 1 இலவசம்', code: 'SNACKFREE', gradient: 'from-orange-500 to-amber-400', icon: 'fa-cookie' },
      { id: 3, title: 'வார இறுதி சிறப்பு', desc: '₹50 கேஷ்பேக்', code: 'WKD50', gradient: 'from-violet-600 to-fuchsia-500', icon: 'fa-star' },
      { id: 4, title: 'புதிய பயனர் சலுகை', desc: '₹100 தள்ளுபடி', code: 'HELLO100', gradient: 'from-emerald-600 to-teal-400', icon: 'fa-gift' },
    ]
  },
  te: {
    cart_title: "స్మార్ట్ ట్రాలీ",
    live_load: "లైవ్ లోడ్",
    subtotal: "మొత్తం",
    syncing: "డేటా సింక్ అవుతోంది...",
    syncing_sub: "బరువు మార్పును సరిపోల్చడం.",
    security_flag: "భద్రతా హెచ్చరిక",
    unscanned_detected: "స్కాన్ చేయని వస్తువులు ఉన్నాయి.",
    items_count: "కార్ట్ వస్తువులు",
    guide_title: "మార్గదర్శి",
    optimized_path: "అనుకూల మార్గం",
    pick_here: "ఇక్కడ తీసుకోండి",
    walking: "దూరం",
    meters: "మీటర్లు",
    list_title: "నా జాబితా",
    hunter_placeholder: "నేడు ఏమి కొంటున్నారు?",
    deals_title: "ఆఫర్లు",
    scan_req: "స్కాన్ అవసరం",
    verified: "ధృవీకరించబడింది",
    reset: "ట్రాలీని రీసెట్ చేయండి",
    empty_cart: "మీ ట్రాలీ ఖాళీగా ఉంది...",
    personal_planner: "పర్సనల్ ప్లానర్",
    gps_linked: "GPS లింక్",
    list_empty: "జాబితా ఖాళీగా ఉంది",
    up_next: "తదుపరి వస్తువు",
    main_dest: "ప్రధాన గమ్యం",
    scan_tip: "వస్తువులను తీసుకోగానే స్కాన్ చేయండి.",
    billing_title: "ఆర్డర్ సారాంశం",
    unscanned_alert: "స్కాన్ చేయని వస్తువులు ఉన్నాయి",
    unscanned_desc: "చెల్లింపుకు ముందు స్కాన్ చేయండి.",
    gst: "GST (18%)",
    grand_total: "మొత్తం ధర",
    pay_qr: "UPI QR స్కాన్",
    pay_card: "కార్డు ద్వారా చెల్లించండి",
    pay_success: "చెల్లింపు విజయవంతమైంది!",
    receipt_sent: "రశీదు పంపబడింది.",
    close_new: "కొత్త షాపింగ్ ప్రారంభించండి",
    claim: "పొందండి",
    empty_billing_prompt: "బిల్లును రూపొందించడానికి వస్తువులను జోడించండి",
    receipt_header: "స్మార్ట్ స్టోర్ రశీదు",
    txn_id: "ట్రాన్సాక్షన్ ఐడి",
    scan_to_pay: "చెల్లించడానికి స్కాన్ చేయండి",
    terminal: "స్టోర్ టెర్మినల్",
    confirm_payment: "చెల్లింపును ధృవీకరించండి",
    cancel: "రద్దు చేయండి",
    code_label: "కోడ్",
    north_facing: "ఉత్తరం వైపు",
    products: {
      '89012345': 'ప్రీమియం బిస్కెట్లు',
      '89056789': 'తాజా పాలు 1లీ',
      '89098765': 'చాక్లెట్ బార్',
      '89011223': 'నూడుల్స్',
      '89033445': 'పండ్ల రసం 1లీ',
      'unknown': 'స్కాన్ చేయని వస్తువు'
    },
    offers: DEFAULT_OFFERS
  },
  ml: {
    cart_title: "സ്മാർട്ട് ട്രോളി",
    live_load: "തത്സമയ ഭാരം",
    subtotal: "ആകെ തുക",
    syncing: "വിവരങ്ങൾ പുതുക്കുന്നു...",
    syncing_sub: "ഭാരവ്യത്യാസം പരിശോധിക്കുന്നു.",
    security_flag: "സുരക്ഷാ മുന്നറിയിപ്പ്",
    unscanned_detected: "സ്കാൻ ചെയ്യാത്ത സാധനങ്ങൾ ഉണ്ട്.",
    items_count: "കാർട്ടിലെ സാധനങ്ങൾ",
    guide_title: "വഴികാട്ടി",
    optimized_path: "മികച്ച വഴി",
    pick_here: "ഇവിടെ നിന്ന് എടുക്കുക",
    walking: "ദൂരം",
    meters: "മീറ്റർ",
    list_title: "എന്റെ ലിസ്റ്റ്",
    hunter_placeholder: "ഇന്ന് എന്താണ് വാങ്ങുന്നത്?",
    deals_title: "ഓഫറുകൾ",
    scan_req: "സ്കാൻ ചെയ്യുക",
    verified: "പരിശോധിച്ചു",
    reset: "ട്രോളി ഒഴിവാക്കുക",
    empty_cart: "കാർട്ട് ശൂന്യമാണ്...",
    personal_planner: "പേഴ്സണൽ പ്ലാനർ",
    gps_linked: "ജിപിഎസ് ലിങ്ക്",
    list_empty: "ലിസ്റ്റ് ശൂന്യമാണ്",
    up_next: "അടുത്തത്",
    main_dest: "പ്രധാന ലക്ഷ്യം",
    scan_tip: "സാധനങ്ങൾ എടുക്കുമ്പോൾ സ്കാൻ ചെയ്യുക.",
    billing_title: "ബില്ലിംഗ്",
    unscanned_alert: "സ്കാൻ ചെയ്യാത്ത സാധനങ്ങൾ",
    unscanned_desc: "പേയ്മെന്റിന് മുൻപ് സ്കാൻ ചെയ്യുക.",
    gst: "ജിഎസ്ടി (18%)",
    grand_total: "ആകെ തുക",
    pay_qr: "യുപിഐ ക്യുആർ സ്കാൻ",
    pay_card: "കാർഡ് വഴി പേ ചെയ്യുക",
    pay_success: "പേയ്മെന്റ് വിജയിച്ചു!",
    receipt_sent: "ഡിജിറ്റൽ രസീത് അയച്ചു.",
    close_new: "പുതിയ ഷോപ്പിംഗ്",
    claim: "നേടുക",
    empty_billing_prompt: "ബിൽ ജനറേറ്റ് ചെയ്യാൻ സാധനങ്ങൾ ചേർക്കുക",
    receipt_header: "സ്മാർട്ട് സ്റ്റോർ രസീത്",
    txn_id: "ട്രാൻസാക്ഷൻ ഐഡി",
    scan_to_pay: "പേ ചെയ്യാൻ സ്കാൻ ചെയ്യുക",
    terminal: "സ്റ്റോർ ടെർമിനൽ",
    confirm_payment: "പേയ്മെന്റ് ഉറപ്പാക്കുക",
    cancel: "റദ്ദാക്കുക",
    code_label: "കോഡ്",
    north_facing: "വടക്കോട്ട്",
    products: {
      '89012345': 'ബിസ്കറ്റ്',
      '89056789': 'പാൽ 1ലി',
      '89098765': 'ചോക്ലേറ്റ്',
      '89011223': 'നൂഡിൽസ്',
      '89033445': 'ജ്യൂസ് 1ലി',
      'unknown': 'സ്കാൻ ചെയ്യാത്തത്'
    },
    offers: DEFAULT_OFFERS
  },
  kn: {
    cart_title: "ಸ್ಮಾರ್ಟ್ ಟ್ರಾಲಿ",
    live_load: "ತೂಕ",
    subtotal: "ಒಟ್ಟು",
    syncing: "ಮಾಹಿತಿ ಸಿಂಕ್ ಆಗುತ್ತಿದೆ...",
    syncing_sub: "ತೂಕದ ಬದಲಾವಣೆ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ.",
    security_flag: "ಸುರಕ್ಷತಾ ಎಚ್ಚರಿಕೆ",
    unscanned_detected: "ಸ್ಕ್ಯಾನ್ ಮಾಡದ ವಸ್ತುಗಳು ಇವೆ.",
    items_count: "ವಸ್ತುಗಳು",
    guide_title: "ಮಾರ್ಗದರ್ಶಿ",
    optimized_path: "ಅನುಕೂಲಕರ ಮಾರ್ಗ",
    pick_here: "ಇಲ್ಲಿಂದ ಆರಿಸಿ",
    walking: "ದೂರ",
    meters: "ಮೀಟರ್",
    list_title: "ನನ್ನ ಪಟ್ಟಿ",
    hunter_placeholder: "ಇಂದು ಏನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?",
    deals_title: "ಕೊಡುಗೆಗಳು",
    scan_req: "ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    verified: "ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    reset: "ಟ್ರಾಲಿ ಮರುಹೊಂದಿಸಿ",
    empty_cart: "ಟ್ರಾಲಿ ಖಾಲಿ ಇದೆ...",
    personal_planner: "ವೈಯಕ್ತಿಕ ಪ್ಲಾನರ್",
    gps_linked: "ಜಿಪಿಎಸ್ ಸಂಪರ್ಕ",
    list_empty: "ಪಟ್ಟಿ ಖಾಲಿ ಇದೆ",
    up_next: "ಮುಂದಿನದು",
    main_dest: "ಮುಖ್ಯ ಗಮ್ಯಸ್ಥಾನ",
    scan_tip: "ವಸ್ತುಗಳನ್ನು ತೆಗೆದುಕೊಂಡಾಗ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ.",
    billing_title: "ಬಿಲ್ಲಿಂಗ್ ವಿವರ",
    unscanned_alert: "ಸ್ಕ್ಯಾನ್ ಮಾಡದ ವಸ್ತುಗಳಿವೆ",
    unscanned_desc: "ಪಾವತಿಗೆ ಮೊದಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ.",
    gst: "ಜಿಎಸ್‌ಟಿ (18%)",
    grand_total: "ಒಟ್ಟು ಮೊತ್ತ",
    pay_qr: "UPI QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    pay_card: "ಕಾರ್ಡ್ ಮೂಲಕ ಪಾವತಿಸಿ",
    pay_success: "ಪಾವತಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
    receipt_sent: "ರಸೀದಿಯನ್ನು ಕಳುಹಿಸಲಾಗಿದೆ.",
    close_new: "ಹೊಸ ಶಾಪಿನಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
    claim: "ಪಡೆಯಿರಿ",
    empty_billing_prompt: "ಬಿಲ್ ತಯಾರಿಸಲು ವಸ್ತುಗಳನ್ನು ಸೇರಿಸಿ",
    receipt_header: "ಸ್ಮಾರ್ಟ್ ಸ್ಟೋರ್ ರಸೀದಿ",
    txn_id: "ವಹಿವಾಟು ಐಡಿ",
    scan_to_pay: "ಪಾವತಿಸಲು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
    terminal: "ಸ್ಟೋರ್ ಟರ್ಮಿನಲ್",
    confirm_payment: "ಪಾವತಿ ಖಚಿತಪಡಿಸಿ",
    cancel: "ರದ್ದುಮಾಡಿ",
    code_label: "ಕೋಡ್",
    north_facing: "ಉತ್ತರಾಭಿಮುಖ",
    products: {
      '89012345': 'ಬಿಸ್ಕೆಟ್',
      '89056789': 'ಹಾಲು 1ಲಿ',
      '89098765': 'ಚಾಕೊಲೇಟ್',
      '89011223': 'ನೂಡಲ್ಸ್',
      '89033445': 'ಜ್ಯೂಸ್ 1ಲಿ',
      'unknown': 'ಸ್ಕ್ಯಾನ್ ಮಾಡದ ವಸ್ತು'
    },
    offers: DEFAULT_OFFERS
  },
  ur: {
    cart_title: "اسمارٹ ٹرالی",
    live_load: "براہ راست وزن",
    subtotal: "مجموعی رقم",
    syncing: "ڈیٹا ہم آہنگ ہو رہا ہے...",
    syncing_sub: "وزن کی تبدیلی کا ملاپ۔",
    security_flag: "سیکیورٹی الرٹ",
    unscanned_detected: "غیر اسکین شدہ اشیاء ملی ہیں۔",
    items_count: "کارٹ اشیاء",
    guide_title: "گائیڈ",
    optimized_path: "راستہ بہتر بنایا گیا",
    pick_here: "یہاں سے اٹھائیں",
    walking: "فاصلہ",
    meters: "میٹر",
    list_title: "میری فہرست",
    hunter_placeholder: "آج آپ کیا ڈھونڈ رہے ہیں؟",
    deals_title: "آفرز",
    scan_req: "اسکین ضروری ہے",
    verified: "تصدیق شدہ",
    reset: "ٹرالی خالی کریں",
    empty_cart: "آپ کی ٹرالی خالی ہے...",
    personal_planner: "پرسنل پلانر",
    gps_linked: "جی پی ایس لنک",
    list_empty: "فہرست خالی ہے",
    up_next: "اگلی چیز",
    main_dest: "اہم منزل",
    scan_tip: "اشیاء اٹھاتے وقت اسکین کریں۔",
    billing_title: "آرڈر کی تفصیل",
    unscanned_alert: "غیر اسکین شدہ اشیاء ملی ہیں",
    unscanned_desc: "ادائیگی سے پہلے اسکین کریں۔",
    gst: "جی ایس ٹی (18%)",
    grand_total: "کل رقم",
    pay_qr: "UPI QR اسکین کریں",
    pay_card: "کارڈ سے ادائیگی",
    pay_success: "ادائیگی کامیاب رہی!",
    receipt_sent: "رسید آپ کو بھیج دی گئی ہے۔",
    close_new: "بند کریں اور دوبارہ شروع کریں",
    claim: "حاصل کریں",
    empty_billing_prompt: "بل بنانے کے لیے اشیاء شامل کریں",
    receipt_header: "اسمارٹ اسٹور رسید",
    txn_id: "ٹرانزیکشن آئی ڈی",
    scan_to_pay: "ادائیگی کے لیے اسکین کریں",
    terminal: "اسٹور ٹرمینل",
    confirm_payment: "ادائیگی کی تصدیق کریں",
    cancel: "منسوخ کریں",
    code_label: "کوڈ",
    north_facing: "شمال کی طرف",
    products: {
      '89012345': 'بسکوٹ',
      '89056789': 'تازہ دودھ',
      '89098765': 'چاکلیٹ',
      '89011223': 'نوڈلز',
      '89033445': 'جوس',
      'unknown': 'غیر اسکین شدہ'
    },
    offers: DEFAULT_OFFERS
  },
  bn: {
    cart_title: "স্মার্ট ট্রলি",
    live_load: "ওজন",
    subtotal: "মোট",
    syncing: "ডেটা সিঙ্ক হচ্ছে...",
    syncing_sub: "ওজন পরিবর্তন পরীক্ষা করা হচ্ছে।",
    security_flag: "নিরাপত্তা সতর্কতা",
    unscanned_detected: "স্ক্যান না করা পণ্য পাওয়া গেছে।",
    items_count: "কার্ট আইটেম",
    guide_title: "গাইড",
    optimized_path: "অপ্টিমাইজড পথ",
    pick_here: "এখান থেকে নিন",
    walking: "দূরত্ব",
    meters: "মিটার",
    list_title: "আমার তালিকা",
    hunter_placeholder: "আজ কি খুঁজছেন?",
    deals_title: "অফার",
    scan_req: "স্ক্যান প্রয়োজন",
    verified: "যাচাইকৃত",
    reset: "ট্রলি খালি করুন",
    empty_cart: "আপনার ট্রলি খালি...",
    personal_planner: "ব্যক্তিগত প্ল্যানার",
    gps_linked: "জিপিএস লিঙ্ক",
    list_empty: "তালিকা খালি",
    up_next: "পরবর্তী আইটেম",
    main_dest: "প্রধান গন্তব্য",
    scan_tip: "পণ্য তোলার সময় স্ক্যান করুন।",
    billing_title: "বিলের সারসংক্ষেপ",
    unscanned_alert: "স্ক্যান না করা পণ্য আছে",
    unscanned_desc: "পেমেন্টের আগে পণ্য স্ক্যান করুন।",
    gst: "জিএসটি (১৮%)",
    grand_total: "মোট টাকা",
    pay_qr: "ইউপিআই কিউআর স্ক্যান করুন",
    pay_card: "কার্ড দিয়ে পেমেন্ট",
    pay_success: "পেমেন্ট সফল!",
    receipt_sent: "রসিদ পাঠানো হয়েছে।",
    close_new: "নতুন কেনাকাটা শুরু করুন",
    claim: "দাবি করুন",
    empty_billing_prompt: "বিল জেনারেট করতে আইটেম যোগ করুন",
    receipt_header: "স্মার্ট স্টোর রসিদ",
    txn_id: "লেনদেন আইডি",
    scan_to_pay: "পেমেন্ট করতে স্ক্যান করুন",
    terminal: "স্টোর টার্মিনাল",
    confirm_payment: "পেমেন্ট নিশ্চিত করুন",
    cancel: "বাতিল করুন",
    code_label: "কোড",
    north_facing: "উত্তরমুখী",
    products: {
      '89012345': 'বিস্কুট',
      '89056789': 'দুধ ১ লিটার',
      '89098765': 'চকলেট বার',
      '89011223': 'নুডলস',
      '89033445': 'জুস ১ লিটার',
      'unknown': 'স্ক্যান না করা পণ্য'
    },
    offers: DEFAULT_OFFERS
  }
};
